# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.point import Point  # noqa: F401,E501
from swagger_server import util


class BodyDetect(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, image_url: str=None, corners: List[Point]=None):  # noqa: E501
        """BodyDetect - a model defined in Swagger

        :param image_url: The image_url of this BodyDetect.  # noqa: E501
        :type image_url: str
        :param corners: The corners of this BodyDetect.  # noqa: E501
        :type corners: List[Point]
        """
        self.swagger_types = {
            'image_url': str,
            'corners': List[Point]
        }

        self.attribute_map = {
            'image_url': 'imageUrl',
            'corners': 'corners'
        }
        self._image_url = image_url
        self._corners = corners

    @classmethod
    def from_dict(cls, dikt) -> 'BodyDetect':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body_detect of this BodyDetect.  # noqa: E501
        :rtype: BodyDetect
        """
        return util.deserialize_model(dikt, cls)

    @property
    def image_url(self) -> str:
        """Gets the image_url of this BodyDetect.


        :return: The image_url of this BodyDetect.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this BodyDetect.


        :param image_url: The image_url of this BodyDetect.
        :type image_url: str
        """

        self._image_url = image_url

    @property
    def corners(self) -> List[Point]:
        """Gets the corners of this BodyDetect.


        :return: The corners of this BodyDetect.
        :rtype: List[Point]
        """
        return self._corners

    @corners.setter
    def corners(self, corners: List[Point]):
        """Sets the corners of this BodyDetect.


        :param corners: The corners of this BodyDetect.
        :type corners: List[Point]
        """

        self._corners = corners
