# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Classnames(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, classnames: str=None):  # noqa: E501
        """Classnames - a model defined in Swagger

        :param classnames: The classnames of this Classnames.  # noqa: E501
        :type classnames: str
        """
        self.swagger_types = {
            'classnames': str
        }

        self.attribute_map = {
            'classnames': 'classnames'
        }
        self._classnames = classnames

    @classmethod
    def from_dict(cls, dikt) -> 'Classnames':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The classnames of this Classnames.  # noqa: E501
        :rtype: Classnames
        """
        return util.deserialize_model(dikt, cls)

    @property
    def classnames(self) -> str:
        """Gets the classnames of this Classnames.


        :return: The classnames of this Classnames.
        :rtype: str
        """
        return self._classnames

    @classnames.setter
    def classnames(self, classnames: str):
        """Sets the classnames of this Classnames.


        :param classnames: The classnames of this Classnames.
        :type classnames: str
        """

        self._classnames = classnames
