# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class KeyValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, key: str=None, value: float=None):  # noqa: E501
        """KeyValue - a model defined in Swagger

        :param key: The key of this KeyValue.  # noqa: E501
        :type key: str
        :param value: The value of this KeyValue.  # noqa: E501
        :type value: float
        """
        self.swagger_types = {
            'key': str,
            'value': float
        }

        self.attribute_map = {
            'key': 'key',
            'value': 'value'
        }
        self._key = key
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'KeyValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The key_value of this KeyValue.  # noqa: E501
        :rtype: KeyValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def key(self) -> str:
        """Gets the key of this KeyValue.


        :return: The key of this KeyValue.
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key: str):
        """Sets the key of this KeyValue.


        :param key: The key of this KeyValue.
        :type key: str
        """

        self._key = key

    @property
    def value(self) -> float:
        """Gets the value of this KeyValue.


        :return: The value of this KeyValue.
        :rtype: float
        """
        return self._value

    @value.setter
    def value(self, value: float):
        """Sets the value of this KeyValue.


        :param value: The value of this KeyValue.
        :type value: float
        """

        self._value = value
